    ####################### Service Configuration #######################
server:
    port: 80

    ####################### Service Discovery Configuration #######################
app:
    billingServerPrefix: https://be-sit.brickparking.com
    myYellowbrickServerPrefix: https://be-sit.brickparking.com/MyYellowbrick
    yellowsoapServerPrefix: https://be-sit.brickparking.com/YellowSoap/rest/v1

    ####################### Database Configuration #######################
spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION = (FAILOVER = ON)(LOAD_BALANCE = ON)(ADDRESS = (PROTOCOL = TCP)(HOST = scan-ybi-tst.waysis.local)(PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = scan-ybi-tst.waysis.local)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = TELEPAY)(FAILOVER_MODE=(TYPE=select)(METHOD=basic))))
    username: TEST_BE_BRICKPARKING
    password: TEST_BE_BRICKPARKING
